Person page
paduc/tresor-de-famille pull request #7
Opened 2022-08-04 13:18 UTC by ClementCHA

On peut maintenant voir sur la page de la personne qui c'est désigné sa famille rapproché au complète: 
- Enfants,
- Parents, 
- Compagnon

TO DO:
- Gérer la récupération via l'url de la TAB sélectionné (Famille/photo)
- Probablement refacto les différents traitements des données venant du gedcom

2022-08-05 14:10 UTC, paduc commented on src/pages/persons/PersonId.route.ts
> +  // @ts-ignore
Ces ts ignore sont une mauvaise habitude.

2022-08-05 14:18 UTC, paduc requested changes

2022-08-05 14:18 UTC, paduc commented on src/pages/persons/PersonIdPage.tsx
> +            {!!companion.length && <RelativeList title='Son/Sa compagne' relatives={companion} />}
Companion -> spouse

2022-08-05 14:18 UTC, paduc commented on src/pages/persons/PersonIdPage.tsx
> +            {!!brotherAndSister.length && <RelativeList title='Ses frères & soeurs' relatives={brotherAndSister} />}
BrotherAndSister => siblings

2022-08-05 14:18 UTC, paduc commented on src/pages/persons/PersonIdPage.tsx
> +            {!!childrens.length && <RelativeList title='Ses enfants' relatives={childrens} />}
Childrens => children

2022-08-05 14:18 UTC, paduc commented on src/pages/persons/PersonId.route.ts
> +  const getPersonRequest = await getPerson()
Crée plutot une query qui te retourne un objet complet (avec tous les props) à destination de ta vue. 

Tu ne devrais pas réutiliser `getGedcom`

2022-08-05 14:18 UTC, paduc commented on src/pages/persons/PersonIdPage.tsx
> +export type PersonIdPage = {
PersonIdPage => PersonPageProps

2022-08-05 14:18 UTC, paduc commented on src/pages/persons/PersonIdPage.tsx
> +export const PersonIdPage = ({ userId, personId, person, parents, childrens, companion, brotherAndSister }: PersonIdPage) => {
PersonIdPage => PersonPage

2022-08-05 20:02 UTC, ClementCHA commented on src/pages/persons/PersonIdPage.tsx
> +            {!!companion.length && <RelativeList title='Son/Sa compagne' relatives={companion} />}
✅

2022-08-05 20:04 UTC, ClementCHA commented on src/pages/persons/PersonIdPage.tsx
> +            {!!brotherAndSister.length && <RelativeList title='Ses frères & soeurs' relatives={brotherAndSister} />}
✅

2022-08-05 20:04 UTC, ClementCHA commented on src/pages/persons/PersonIdPage.tsx
> +            {!!childrens.length && <RelativeList title='Ses enfants' relatives={childrens} />}
✅

2022-08-05 20:06 UTC, ClementCHA commented on src/pages/persons/PersonIdPage.tsx
> +export type PersonIdPage = {
✅

2022-08-05 20:06 UTC, ClementCHA commented on src/pages/persons/PersonIdPage.tsx
> +export const PersonIdPage = ({ userId, personId, person, parents, childrens, companion, brotherAndSister }: PersonIdPage) => {
✅

2022-08-08 08:22 UTC, ClementCHA commented on src/pages/persons/PersonId.route.ts
> +  const getPersonRequest = await getPerson()
Qu'est ce que tu veux dire par là ? 

- Que getGedcom ne devrait pas se retrouver dans ce scope => Je fais une query utilisant getGedcom récupérant un object avec tout ce que je veux  (Mes props) ? 

- Est-ce que je ne dois même pas utiliser getGedcom dans ma query, refaire du coup une query qui ressemble à getGedcom mais qui retournerais une object plus précis ? Pour moi ça fait un peu répétition de code au sein de l'ensemble mais peut être il y a une considération qui m'échappe ?

2022-08-08 08:34 UTC, paduc commented on src/pages/persons/PersonId.route.ts
> +  const getPersonRequest = await getPerson()
1. La logique “récupération de données” ne devrait pas apparaître dans le controlleur de routes (fichier *.route.ts). Elle a sa place dans une query. Une query a la forme `getXXX : (args) => MyViewProps` et doit donc encapsuler toute la logique qui permet d’aboutir aux props attendus pour cette vue spécifique.
2. La réutilisation de code est un cas d’optimisation prématurée. Tu parles de copier-coller parce que tu as l’impression que les deux usages sont très similaires (voire identiques) mais en réalité, ils peuvent diverger et la réutilisation d’un`getGedcom` Générique peut te freiner au moment où ca diverge: tu vas impacter tous les usages de `getGedcom` en voulant l’adapter pour un cas précis. On parle de couplage et c’est ce qu’on veut éviter. Il est donc toujours préférable de commencer par copier la logique dans deux fichiers.

2022-08-08 13:13 UTC, ClementCHA commented on src/pages/persons/PersonId.route.ts
> +  const getPersonRequest = await getPerson()
✅

2022-08-08 16:21 UTC, paduc commented on src/pages/importGedcomSuccess/ImportGedcomSuccessPage.tsx
> +  const [personSearched, setPersonSearched] = React.useState<Person[]>([])
Attention à l’usage d’un type partagé / générique trop tot. Le contexte changeant légèrement (parfois `Person` peut avoir ses relations, parfois non, parfois il peut contenir ses dates de naissance, parfois il peut avoir un lien vers sa photo de profil), tu peux te retrouver à avoir du mal à définir un type réellement générique.

Je sais que ce n’est pas naturel mais il vaut mieux redéfinir le type dans chaque contexte, même s’ils ont des champs en commun (voire même tous).

2022-08-08 16:25 UTC, paduc commented on src/pages/persons/PersonPage.tsx
> +  relationships: {
Tu peux économiser un niveau ici, en mettant directement 
```ts
type PersonPageProps = {
  userId: string
  personId: string
  // …
}
```

2022-08-08 16:27 UTC, paduc commented on src/pages/persons/PersonPage.route.ts
> +  const relationships = await getRelationships()
Est-ce que c’est vraiment des `relationships` ?
J’aurais appelé cette query `getPersonInfo()` 

Puis `responseAtHtml(request, response, PersonPage({ …persoInfo }))`

2022-08-08 16:29 UTC, paduc commented on src/pages/persons/getRelationships.query.ts
> +  const getPersonRequest = await getPerson()
`Pas de réutilisation = pas de couplage ;)

2022-08-08 16:35 UTC, paduc commented on src/pages/persons/getRelationships.query.ts
> +  const getPersonRequest = await getPerson()
Tu peux copier le code de `getPerson` dans le corps de cette requête.

2022-08-08 16:49 UTC, paduc requested changes

2022-08-08 16:49 UTC, paduc commented on src/pages/persons/getRelationships.query.ts
> +  const parents = parentsIds.map((p: string) => persons.find((e: { id: string }) => e.id === p))
Pour augmenter la lisibilité, tu peux découper en plusieurs méthodes, par ex: `const parents = getParents(gedcom, personId)`

Ce serait une méthode synchrone (elle ne fait pas d’appel à la base de données) située dans le même fichier.

Idem pour `getSiblings/getChildren/getSpouses`

2022-08-08 16:49 UTC, paduc commented on src/pages/persons/getRelationships.query.ts
> +  const relationship = {
Ici tu peux retourner l’objet directement. Pas besoin de l’affecter à une variable.

2022-08-08 16:49 UTC, paduc commented on src/types/Relationship.ts
> +export type Relationship = {
Idem que `Person`, à définir sur le lieu de premier usage.

2022-08-08 16:49 UTC, paduc commented on src/pages/persons/getRelationships.query.ts
> +    .map((c: { childId: string }) => c.childId)
Éviter les noms abrégés de variables comme `c` ou `e`.

2022-08-08 16:49 UTC, paduc commented on src/pages/persons/getRelationships.query.ts
> +    .filter((children: { parentId: string }) => children.parentId === personId)
Pas besoin de typer l’argument de `filter`. Il est typé par `relationships`

2022-08-08 16:49 UTC, paduc commented on src/pages/persons/getRelationships.query.ts
> +  const gedcom = rows[0]
`const gedcom = rows[0] as GedcomImported`

Pour profiter du typage de payload.

2022-08-08 16:49 UTC, paduc commented on src/pages/persons/getRelationships.query.ts
> +  const siblingsIds = parentsIds
Ces méthodes sont complexes… ca mérite un test unitaire !

2022-08-09 06:51 UTC, ClementCHA commented on src/pages/persons/PersonPage.route.ts
> +  const relationships = await getRelationships()
✅

2022-08-09 06:53 UTC, ClementCHA commented on src/pages/persons/getRelationships.query.ts
> +  const getPersonRequest = await getPerson()
✅

2022-08-09 06:57 UTC, ClementCHA commented on src/pages/persons/getRelationships.query.ts
> +  const relationship = {
✅

2022-08-09 08:26 UTC, ClementCHA commented on src/pages/persons/getRelationships.query.ts
> +  const { rows } = await postgres.query("SELECT * FROM events where type = 'GedcomImported'")
✅ => ça prend tout de suite plus de temps quand ton userId est égal à request.session.id et pas request.session.user!.id 😒

2022-08-09 08:29 UTC, ClementCHA commented on src/pages/persons/getRelationships.query.ts
> +    .map((c: { childId: string }) => c.childId)
✅

2022-08-09 08:54 UTC, ClementCHA commented on src/pages/persons/getRelationships.query.ts
> +  const parents = parentsIds.map((p: string) => persons.find((e: { id: string }) => e.id === p))
✅

2022-08-09 08:55 UTC, ClementCHA commented on src/types/Relationship.ts
> +export type Relationship = {
✅

2022-08-09 09:04 UTC, ClementCHA commented on src/pages/persons/getRelationships.query.ts
> +    .filter((children: { parentId: string }) => children.parentId === personId)
✅

2022-08-09 09:06 UTC, ClementCHA commented on src/pages/persons/getRelationships.query.ts
> +  const gedcom = rows[0]
✅

2022-08-09 10:01 UTC, paduc commented on src/pages/persons/getPersoInfo.query.ts
> +  const personQuery = await postgres.query("SELECT * FROM events where type = 'UserHasDesignatedHimselfAsPerson'")
Que se passerait-il s’il y a plusieurs événements de type `UserHasDesignatedHimselfAsPerson`? 

`personId` doit passé en paramètre à `getPersonInfo` Comme ça il est possible d’afficher la page de n’importe qui.

2022-08-09 10:02 UTC, paduc commented on src/pages/persons/getPersoInfo.query.ts
> +  const { rows } = await postgres.query("SELECT * FROM events where type = 'GedcomImported' AND payload->>’importedBy’ = $1", [
Idem `userId` doit être passé en paramètre de `getPersonInfo`.

2022-08-09 11:36 UTC, ClementCHA commented on src/pages/persons/getPersoInfo.query.ts
> +  const personQuery = await postgres.query("SELECT * FROM events where type = 'UserHasDesignatedHimselfAsPerson'")
Hm, je ne suis pas sur de comprendre où tu veux en venir. 

personId vient de la query personQuery : 

```
export const getPersonInfo = async () => { 
    const personQuery = await postgres.query("SELECT * FROM events where type = 'UserHasDesignatedHimselfAsPerson'")
  
    const personDesignate = personQuery.rows[0]
  
    const {
      payload: { userId, personId },
    } = personDesignate
    
    ..... 
  }
```

Je ne vois pas trop ce que tu veux dire quand tu dis que personId et userId doivent être passé en paramètre de getPersonInfo? 🤔

2022-08-09 12:28 UTC, ClementCHA commented on src/pages/importGedcomSuccess/ImportGedcomSuccessPage.tsx
> +  const [personSearched, setPersonSearched] = React.useState<Person[]>([])
✅

2022-08-09 14:36 UTC, ClementCHA commented on src/pages/persons/getPersoInfo.query.ts
> +  const spouse = getSpouse(children, relationships, persons, person)
J'ai un problème ici de TS sur children : 
```
const children: (PersonDetailed | undefined)[] | null
Argument of type '(PersonDetailed | undefined)[] | null' is not assignable to parameter of type 'PersonDetailed[]'.
  Type 'null' is not assignable to type 'PersonDetailed[]'.ts
```

Je ne parviens pas à le résoudre. J'ai essayé de mettre des conditions dans getChildren() afin d'exclure la possibilité que ça soit null ou undefined mais rien y fait. Je te demande pas la réponse mais est-ce que tu as une piste pour moi?

2022-08-09 15:37 UTC, paduc commented
Ben écoute teste comme ça. 😇

> Le 9 août 2022 à 13:36, ClementCHA ***@***.***> a écrit :
> 
> ﻿
> @ClementCHA commented on this pull request.
> 
> In src/pages/persons/getPersoInfo.query.ts:
> 
> > @@ -2,23 +2,24 @@ import { postgres } from '../../dependencies/postgres'
>  import { Person } from '../../types/Person'
>  import { Relationship } from '../../types/Relationship'
>  
> -import { getPerson } from './getPerson.query'
> +export const getPersonInfo = async () => {
> +  const personQuery = await postgres.query("SELECT * FROM events where type = 'UserHasDesignatedHimselfAsPerson'")
> Hm, je ne suis pas sur de comprendre où tu veux en venir.
> 
> personId vient de la query personQuery :
> 
> export const getPersonInfo = async () => { 
>     const personQuery = await postgres.query("SELECT * FROM events where type = 'UserHasDesignatedHimselfAsPerson'")
>   
>     const personDesignate = personQuery.rows[0]
>   
>     const {
>       payload: { userId, personId },
>     } = personDesignate
>     
>     ..... 
>   }
> Je ne vois pas trop ce que tu veux dire quand tu dis que personId et userId doivent être passé en paramètre de getPersonInfo? 🤔
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.

2022-08-09 15:45 UTC, ClementCHA commented
> Ben écoute teste comme ça. 😇
> […](#)
> Le 9 août 2022 à 13:36, ClementCHA ***@***.***> a écrit : ﻿ @ClementCHA commented on this pull request. In src/pages/persons/getPersoInfo.query.ts: > @@ -2,23 +2,24 @@ import { postgres } from '../../dependencies/postgres' import { Person } from '../../types/Person' import { Relationship } from '../../types/Relationship' -import { getPerson } from './getPerson.query' +export const getPersonInfo = async () => { + const personQuery = await postgres.query("SELECT * FROM events where type = 'UserHasDesignatedHimselfAsPerson'") Hm, je ne suis pas sur de comprendre où tu veux en venir. personId vient de la query personQuery : export const getPersonInfo = async () => { const personQuery = await postgres.query("SELECT * FROM events where type = 'UserHasDesignatedHimselfAsPerson'") const personDesignate = personQuery.rows[0] const { payload: { userId, personId }, } = personDesignate ..... } Je ne vois pas trop ce que tu veux dire quand tu dis que personId et userId doivent être passé en paramètre de getPersonInfo? 🤔 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

=> Je remarque bien que je tombe toujours sur la même page profil quelque soit la personne que je choisis avec le "C'est moi" 😬

2022-08-09 17:48 UTC, ClementCHA commented on src/pages/persons/PersonPage.tsx
> +  relationships: {
✅

2022-08-09 17:48 UTC, ClementCHA commented on src/pages/persons/getPersoInfo.query.ts
> +  const personQuery = await postgres.query("SELECT * FROM events where type = 'UserHasDesignatedHimselfAsPerson'")
✅

2022-08-09 17:48 UTC, ClementCHA commented on src/pages/persons/getPersoInfo.query.ts
> +  const { rows } = await postgres.query("SELECT * FROM events where type = 'GedcomImported' AND payload->>’importedBy’ = $1", [
✅

2022-08-18 16:53 UTC, paduc requested changes
La fonction que tu veux tester est la query `getPersonInfo.query.ts`, la méthode qui est appelée par la route pour récupérer.

Il faut donc tester la méthode `getPersonInfo = ({ userId, personId }) : PersonPageProps`, celle qui fait des requêtes sur la db, c'est ce qui en fait un test d'intégration.

Pour cela, tu vas commencer par appeler `resetDatabase` et injecter des données de test dans la db. 

Ensuite tu vas appeler la query elle-même et vérifier qu'elle te retourne les bonnes valeurs.

De cette manière, le test sera indépendant de l'implémentation, et tu pourras utiliser le test pour refactorer l'implémentation.

2023-10-30 18:53 UTC, closed without merging